apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-app
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-java-app